name         'puppet-networkmanager'
version      '0.0.1'
dependency   'puppetlabs/stdfile'
source       'https://github.com/arjenderijke/puppet-networkmanager'
author       'arjenderijke'
summary      'Puppet NetworkManager Module'
description  'Puppet module to manage NetworkManager service and connections'
project_page 'https://github.com/arjenderijke/puppet-networkmanager'
